spring:
  application:
    name: user-name
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/rainsun_space

server:
  port: 8080

